services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASSWORD=userpass
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=ticketbooking_db
      - JWT_SECRET=@iwakpeyeK23_$$eg00p3ceL
      - PORT=8080
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=iwakpeyek23
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ticketbooking_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
