// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://example.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support",
            "email": "support@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/activities/alerts": {
            "get": {
                "responses": {}
            }
        },
        "/activities/summary/{userID}": {
            "get": {
                "responses": {}
            }
        },
        "/api/events": {
            "post": {
                "responses": {}
            }
        },
        "/api/events/": {
            "get": {
                "responses": {}
            }
        },
        "/api/events/{id}": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        },
        "/api/tickets": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/api/tickets/{id}": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        },
        "/api/users/{id}/tickets": {
            "get": {
                "responses": {}
            }
        },
        "/auth/login": {
            "post": {
                "responses": {}
            }
        },
        "/auth/logout": {
            "post": {
                "responses": {}
            }
        },
        "/auth/register": {
            "post": {
                "responses": {}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "BookTicket API",
	Description:      "This is the BookTicket Data Management API documentation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
